export const RPC = {
  listOrganizations: 'depot.core.v1.OrganizationService/ListOrganizations',
  listProjects: 'depot.core.v1.ProjectService/ListProjects',
  getProject: 'depot.core.v1.ProjectService/GetProject',
  listTrustPolicies: 'depot.core.v1.ProjectService/ListTrustPolicies',
  listBuilds: 'depot.core.v1.BuildService/ListBuilds',
  getBuild: 'depot.core.v1.BuildService/GetBuild',
  getBuildSteps: 'depot.build.v1.BuildService/GetBuildSteps',
  getBuildStepLogs: 'depot.build.v1.BuildService/GetBuildStepLogs',
  listImages: 'depot.build.v1.RegistryService/ListImages',
  getUsage: 'depot.core.v1.UsageService/GetUsage',
  getProjectUsage: 'depot.core.v1.UsageService/GetProjectUsage',
  listRuns: 'depot.ci.v1.CIService/ListRuns',
  getRun: 'depot.ci.v1.CIService/GetRun',
  getRunStatus: 'depot.ci.v1.CIService/GetRunStatus',
  getFailureDiagnosis: 'depot.ci.v1.CIService/GetFailureDiagnosis',
  getJobAttemptLogs: 'depot.ci.v1.CIService/GetJobAttemptLogs',
  getJobSummary: 'depot.ci.v1.CIService/GetJobSummary',
  getJobAttemptMetrics: 'depot.ci.v1.CIService/GetJobAttemptMetrics',
  listArtifacts: 'depot.ci.v1.CIService/ListArtifacts',
  getArtifactDownloadUrl: 'depot.ci.v1.CIService/GetArtifactDownloadURL',
  listSecrets: 'depot.ci.v3beta2.SecretService/ListSecrets',
  listVariables: 'depot.ci.v3beta2.VariableService/ListVariables',
  // Beta surfaces, reachable only with DEPOT_MCP_ENABLE_BETA.
  listSandboxes: 'depot.sandbox.v1.SandboxService/ListSandboxes',
  getSandbox: 'depot.sandbox.v1.SandboxService/GetSandbox',
  listRegistryRepositories: 'depot.registry.v1beta1.RegistryService/ListRepositories',
  listRegistryImages: 'depot.registry.v1beta1.RegistryService/ListImages',
  getRegistryImageDetail: 'depot.registry.v1beta1.RegistryService/GetImageDetail',
  getRegistryRetentionPolicy: 'depot.registry.v1beta1.RegistryService/GetRetentionPolicy',
} as const;
