import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { DepotMcpConfig } from './config.js';
import { DepotApi } from './depot/api.js';
import { DepotClient, type FetchLike } from './depot/client.js';
import { registerPrompts } from './prompts.js';
import { registerTools, type RegistrationSummary } from './tools/index.js';

export const SERVER_NAME = 'depot-mcp';
export const SERVER_VERSION = '0.1.0';

export interface CreateServerOptions {
  readonly config: DepotMcpConfig;
  /** Injected by the test suite so tools can run against recorded fixtures. */
  readonly fetch?: FetchLike | undefined;
  readonly sleep?: ((ms: number) => Promise<void>) | undefined;
}

export interface CreatedServer {
  readonly server: McpServer;
  readonly registration: RegistrationSummary;
}

export function createServer(options: CreateServerOptions): CreatedServer {
  const client = new DepotClient({
    token: options.config.token,
    apiUrl: options.config.apiUrl,
    orgId: options.config.orgId,
    fetch: options.fetch,
    sleep: options.sleep,
  });

  const server = new McpServer(
    { name: SERVER_NAME, version: SERVER_VERSION },
    {
      instructions: [
        'Read-only access to depot.dev: Depot CI runs and failures, container build history, projects, registry images, CI configuration, and usage.',
        '',
        'For any "why did this fail" question, call depot_diagnose_ci_failure (Depot CI) or depot_diagnose_build (container builds) before fetching logs. Both return a bounded, pre-analysed result; raw logs are the fallback, not the first step.',
        'If a list comes back empty or a call is denied, call depot_whoami — the usual cause is a token that spans several organizations without DEPOT_ORG_ID set.',
        'Every tool here is read-only. Nothing can trigger, retry, cancel, or delete anything, and container builds cannot be started through Depot\'s API at all.',
        'Failure diagnoses and suggested fixes are generated by Depot\'s AI and can be wrong; verify them against the evidence lines they come with.',
      ].join('\n'),
    },
  );

  const context = { api: new DepotApi(client), config: options.config };
  const registration = registerTools(server, context);
  registerPrompts(server);

  return { server, registration };
}
