import { z } from 'zod';
import { DepotApiError } from '../depot/errors.js';
import type { JsonObject } from '../depot/shape.js';
import { TextBudget } from '../lib/budget.js';
import { parseDiagnosis, type AttemptRef, type Diagnosis } from '../lib/diagnosis.js';
import {
  CI_TARGET_TYPES,
  candidateTargetTypes,
  toDiagnosisTargetType,
  type CiTargetType,
} from '../lib/resolve.js';
import { defineTool, ToolInputError, type ToolContext } from '../lib/tool.js';

const DESCRIPTION = `Explain why a Depot CI run, workflow, job, or attempt failed.

Reach for this first whenever someone asks why CI failed, what broke the build, or to fix a failing job. It calls Depot's server-side failure analysis, which clusters every failure in the target by root cause and returns, for each cluster: the error message, an AI-written diagnosis, a suggested fix, and the exact log lines that are the evidence.

Prefer this over depot_get_ci_logs. Depot bounds this response server-side, so it costs far less context than raw logs, and it already works out which job is the real root cause rather than a downstream casualty. Use depot_get_ci_logs afterwards only if you need more detail on a specific attempt.

Pass whichever identifier you have in "id" — a run, workflow, job, or attempt ID. This server works out which kind it is; set "targetType" only when you already know it and want to skip that step.

How to read the returned "state":
- "focused_failure": one clear culprit. Read representativeAttempts.
- "grouped_failures": several distinct root causes, clustered by fingerprint. Read failureGroups.
- "over_limit": too many failures to analyse at this level. narrowerTargets gives the IDs to call this tool again with.
- "empty": Depot found no failure evidence. The target may still be running, may have succeeded, or may be old enough that its logs have aged out.

Diagnoses and suggested fixes are generated by Depot's AI and can be wrong — treat them as a lead to verify, not a fact. Read-only: this never retries, cancels, or triggers anything.`;

const evidenceSchema = z.object({
  stepId: z.string().optional(),
  lineNumber: z.number().optional(),
  content: z.string(),
  contentTruncated: z.boolean(),
});

const attemptSchema = z.object({
  attemptId: z.string().optional(),
  jobId: z.string().optional(),
  jobKey: z.string().optional(),
  attempt: z.number().optional(),
  attemptStatus: z.string().optional(),
  attemptConclusion: z.string().optional(),
  errorMessage: z.string().optional(),
  diagnosis: z.string().optional(),
  possibleFix: z.string().optional(),
  evidence: z.array(evidenceSchema),
  evidenceOmitted: z.number(),
});

const nextStepSchema = z.object({
  kind: z.string(),
  label: z.string().optional(),
  tool: z.string().optional(),
  arguments: z.record(z.string(), z.string()),
});

const inputSchema = {
  id: z
    .string()
    .min(1)
    .describe(
      'A Depot CI identifier: a run, workflow, job, or attempt ID. Pass whatever you have — the server resolves which kind it is.',
    ),
  targetType: z
    .enum(CI_TARGET_TYPES)
    .optional()
    .describe(
      'What kind of thing "id" refers to. Omit unless you know it; the server otherwise infers it, falling back to trying each kind in turn.',
    ),
  maxFailureGroups: z
    .number()
    .int()
    .min(1)
    .max(20)
    .default(5)
    .describe('Cap on how many clustered root causes to return. Raise only if 5 was not enough.'),
  maxEvidenceLines: z
    .number()
    .int()
    .min(0)
    .max(60)
    .default(15)
    .describe(
      'Cap on evidence log lines per failing attempt. Set 0 to get diagnoses and fixes without any log lines.',
    ),
};

const outputSchema = {
  state: z
    .string()
    .describe('One of focused_failure, grouped_failures, over_limit, empty, or unknown.'),
  resolvedTargetType: z.string().describe('The target kind that Depot accepted for this id.'),
  emptyReason: z.string().optional(),
  target: z.object({
    targetId: z.string().optional(),
    targetType: z.string().optional(),
    status: z.string().optional(),
  }),
  context: z.object({
    repo: z.string().optional(),
    ref: z.string().optional(),
    sha: z.string().optional(),
    trigger: z.string().optional(),
    runId: z.string().optional(),
    runStatus: z.string().optional(),
    workflowId: z.string().optional(),
    workflowName: z.string().optional(),
    workflowPath: z.string().optional(),
    workflowStatus: z.string().optional(),
    jobId: z.string().optional(),
    jobKey: z.string().optional(),
    jobDisplayName: z.string().optional(),
    jobStatus: z.string().optional(),
    jobConclusion: z.string().optional(),
    attemptId: z.string().optional(),
    attempt: z.number().optional(),
    attemptStatus: z.string().optional(),
    truncatedContextFields: z.array(z.string()),
  }),
  failureGroups: z.array(
    z.object({
      fingerprint: z.string().optional(),
      source: z.string().optional(),
      count: z.number().optional(),
      errorMessage: z.string().optional(),
      errorMessageTruncated: z.boolean(),
      diagnosis: z.string().optional(),
      possibleFix: z.string().optional(),
      attempts: z.array(attemptSchema),
      omittedRepresentativeCount: z.number().optional(),
    }),
  ),
  representativeAttempts: z.array(attemptSchema),
  narrowerTargets: z
    .array(
      z.object({
        targetType: z.string().optional(),
        targetId: z.string().optional(),
        label: z.string().optional(),
        status: z.string().optional(),
        failedJobCount: z.number().optional(),
        nextStep: nextStepSchema.optional(),
      }),
    )
    .describe('Present when state is over_limit: narrower ids to re-run this tool against.'),
  nextSteps: z
    .array(nextStepSchema)
    .describe("Depot's suggested follow-ups, rewritten as calls to this server's tools."),
  truncation: z.object({
    byDepot: z.boolean(),
    byServer: z.boolean(),
    omittedFailureGroups: z.number(),
    omittedAttempts: z.number(),
    notes: z.array(z.string()),
  }),
  aiDisclosure: z.string().optional(),
};

function describeAttempt(attempt: AttemptRef): string {
  const parts: string[] = [];
  parts.push(attempt.jobKey === undefined ? 'job' : `job "${attempt.jobKey}"`);
  if (attempt.attempt !== undefined) {
    parts.push(`attempt ${attempt.attempt}`);
  }
  const state = attempt.attemptConclusion ?? attempt.attemptStatus;
  if (state !== undefined) {
    parts.push(`(${state})`);
  }
  if (attempt.attemptId !== undefined) {
    parts.push(`attemptId=${attempt.attemptId}`);
  }
  return parts.join(' ');
}

function pushAttemptDetail(text: TextBudget, attempt: AttemptRef, indent: string): void {
  text.push(`${indent}${describeAttempt(attempt)}`);
  if (attempt.errorMessage !== undefined) {
    text.push(`${indent}  error: ${attempt.errorMessage}`);
  }
  if (attempt.diagnosis !== undefined) {
    text.push(`${indent}  diagnosis: ${attempt.diagnosis}`);
  }
  if (attempt.possibleFix !== undefined) {
    text.push(`${indent}  possible fix: ${attempt.possibleFix}`);
  }
  for (const line of attempt.evidence) {
    const step = line.stepId === undefined ? '' : `[${line.stepId}] `;
    const number = line.lineNumber === undefined ? '' : `L${line.lineNumber} `;
    text.push(`${indent}  | ${step}${number}${line.content}`);
  }
  if (attempt.evidenceOmitted > 0) {
    text.push(`${indent}  (${attempt.evidenceOmitted} more evidence line(s) not shown)`);
  }
}

function renderContextLine(diagnosis: Diagnosis): string | undefined {
  const { context } = diagnosis;
  const parts: string[] = [];
  if (context.repo !== undefined) {
    parts.push(context.sha === undefined ? context.repo : `${context.repo}@${context.sha}`);
  }
  if (context.ref !== undefined) {
    parts.push(`ref ${context.ref}`);
  }
  if (context.trigger !== undefined) {
    parts.push(`trigger ${context.trigger}`);
  }
  if (context.workflowName !== undefined) {
    parts.push(
      context.workflowPath === undefined
        ? `workflow "${context.workflowName}"`
        : `workflow "${context.workflowName}" (${context.workflowPath})`,
    );
  }
  if (context.jobDisplayName !== undefined || context.jobKey !== undefined) {
    parts.push(`job "${context.jobDisplayName ?? context.jobKey ?? ''}"`);
  }
  if (context.runStatus !== undefined) {
    parts.push(`run ${context.runStatus}`);
  }
  return parts.length === 0 ? undefined : `Context: ${parts.join(' · ')}`;
}

function renderDiagnosis(diagnosis: Diagnosis, charBudget: number): string {
  const text = new TextBudget(charBudget);
  const targetLabel = [diagnosis.target.targetType, diagnosis.target.targetId]
    .filter((part) => part !== undefined)
    .join(' ');

  text.push(`Depot CI failure diagnosis (${diagnosis.state}) for ${targetLabel || 'target'}.`);
  const contextLine = renderContextLine(diagnosis);
  if (contextLine !== undefined) {
    text.push(contextLine);
  }

  if (diagnosis.state === 'empty') {
    text.push(
      '',
      `Depot found no failure evidence${
        diagnosis.emptyReason === undefined ? '' : ` (${diagnosis.emptyReason})`
      }.`,
      'This usually means the target has not failed, is still running, or is old enough that its logs have aged out.',
      'Check current status with depot_get_ci_run, or list recent failures with depot_list_ci_runs status=["failed"].',
    );
    return text.render();
  }

  if (diagnosis.state === 'over_limit') {
    text.push(
      '',
      'Too many failures to diagnose at this level. Call depot_diagnose_ci_failure again with one of these narrower targets:',
    );
    for (const target of diagnosis.narrowerTargets) {
      const count =
        target.failedJobCount === undefined ? '' : ` — ${target.failedJobCount} failed job(s)`;
      text.push(
        `  - ${target.targetType ?? 'target'} ${target.targetId ?? '?'}: ${target.label ?? 'unnamed'}${count}`,
      );
    }
  }

  if (diagnosis.failureGroups.length > 0) {
    text.push('', `${diagnosis.failureGroups.length} failure group(s), most significant first:`);
    diagnosis.failureGroups.forEach((group, index) => {
      const occurrences = group.count === undefined ? '' : `${group.count}x `;
      const source = group.source === undefined ? '' : ` [source: ${group.source}]`;
      text.push('', `${index + 1}) ${occurrences}${group.errorMessage ?? 'no error message'}${source}`);
      if (group.diagnosis !== undefined) {
        text.push(`   diagnosis: ${group.diagnosis}`);
      }
      if (group.possibleFix !== undefined) {
        text.push(`   possible fix: ${group.possibleFix}`);
      }
      for (const attempt of group.attempts) {
        pushAttemptDetail(text, attempt, '   ');
      }
      if (group.omittedRepresentativeCount !== undefined && group.omittedRepresentativeCount > 0) {
        text.push(`   (${group.omittedRepresentativeCount} more affected attempt(s) not shown)`);
      }
    });
  }

  if (diagnosis.representativeAttempts.length > 0) {
    text.push('', 'Failing attempts:');
    for (const attempt of diagnosis.representativeAttempts) {
      pushAttemptDetail(text, attempt, '  ');
    }
  }

  if (diagnosis.nextSteps.length > 0) {
    text.push('', 'Suggested next tool calls:');
    for (const step of diagnosis.nextSteps) {
      const call =
        step.tool === undefined
          ? `(no equivalent tool for "${step.kind}")`
          : `${step.tool} ${JSON.stringify(step.arguments)}`;
      text.push(`  - ${call}${step.label === undefined ? '' : ` — ${step.label}`}`);
    }
  }

  if (diagnosis.truncation.notes.length > 0) {
    text.push('', 'Completeness:');
    for (const note of diagnosis.truncation.notes) {
      text.push(`  - ${note}`);
    }
  }

  if (diagnosis.aiDisclosure !== undefined) {
    text.push('', diagnosis.aiDisclosure);
  }

  return text.render();
}

async function fetchDiagnosis(
  context: ToolContext,
  id: string,
  explicit: CiTargetType | undefined,
): Promise<{ response: JsonObject; resolved: CiTargetType }> {
  const candidates = candidateTargetTypes(id, explicit);
  let lastError: DepotApiError | undefined;

  for (const candidate of candidates) {
    try {
      const response = await context.api.getFailureDiagnosis(id, toDiagnosisTargetType(candidate));
      return { response, resolved: candidate };
    } catch (error) {
      const wrongKind =
        error instanceof DepotApiError &&
        (error.code === 'not_found' || error.code === 'invalid_argument');
      if (!wrongKind) {
        throw error;
      }
      lastError = error;
    }
  }

  if (lastError !== undefined && candidates.length === 1) {
    throw lastError;
  }
  throw new ToolInputError(
    `Depot did not recognise "${id}" as a run, workflow, job, or attempt in this organization. Check the id, and check DEPOT_ORG_ID if you belong to more than one organization. Use depot_list_ci_runs to find valid run ids.`,
  );
}

export const diagnoseCiFailureTool = defineTool({
  name: 'depot_diagnose_ci_failure',
  title: 'Diagnose a Depot CI failure',
  description: DESCRIPTION,
  inputSchema,
  outputSchema,
  handler: async (input, context) => {
    const { response, resolved } = await fetchDiagnosis(context, input.id, input.targetType);
    const diagnosis = parseDiagnosis(response, {
      maxFailureGroups: input.maxFailureGroups,
      maxEvidenceLines: input.maxEvidenceLines,
    });

    return {
      summary: renderDiagnosis(diagnosis, context.config.outputCharBudget),
      data: { ...diagnosis, resolvedTargetType: resolved },
    };
  },
});
